# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td_biblio', '0001_initial'),
        ('bims', '0054_auto_20181019_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibliography_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_biblio.Entry')),
                ('biological_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.BiologicalCollectionRecord')),
                ('location_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.LocationSite')),
            ],
        ),
    ]
