apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rancher.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: dbbackups
  name: dbbackups
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dbbackups
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.rancher.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: dbbackups
    spec:
      containers:
        - env:
            - name: DUMPPREFIX
              value: PG_bims
            - name: PGDATABASE
              value: gis
            - name: PGHOST
              value: db
            - name: PGPASSWORD
              value: docker
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: docker
          image: kartoza/pg-backup:9.6
          name: dbbackups
          resources: {}
      hostname: pg-backups
      restartPolicy: Always
status: {}
