apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rancher.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: geoserver
  name: geoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: geoserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.rancher.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: geoserver
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://docker:docker@db:5432/gis
            - name: GEOSERVER_ADMIN_PASSWORD
              value: admingeoserver
            - name: GEOSERVER_ADMIN_USER
              value: admin
            - name: HTTP_HOST
              value: 0.0.0.0
            - name: HTTP_PORT
              value: "63305"
          image: kartoza/geoserver:2.19.0
          name: geoserver
          resources: {}
          volumeMounts:
            - mountPath: /opt/geoserver/data_dir/
              name: geoserver-datadir
      restartPolicy: Always
      volumes:
        - name: geoserver-datadir
          persistentVolumeClaim:
            claimName: geoserver-datadir
status: {}
