name: Build and Push Docker Image

on: 
  push: 
    branches:
      - 'develop_new'

jobs:
  build:	
    name: Build and Push Docker Django BIMS Image	
    runs-on: ubuntu-18.04	
    steps:	
    - uses: actions/checkout@master	
    - name: Build and Publish the Docker Django Bims Image	
      uses: elgohr/Publish-Docker-Github-Action@master	
      with:	
        name: kartoza/kbims_uwsgi:latest
        workdir: deployment/production
        username: ${{ secrets.DOCKER_USERNAME }}	
        password: ${{ secrets.DOCKER_PASSWORD }}	
        buildargs: BIMS_TAG=main
